# Generated by Django 5.0.14 on 2026-09-22 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blueprint', '0001_initial'),
        ('question_bank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_label', models.CharField(help_text='Set A, Set B, Set C ...', max_length=5)),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='generated_papers/')),
                ('answer_key_file', models.FileField(blank=True, null=True, upload_to='answer_keys/')),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_papers', to='blueprint.blueprint')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_on'],
            },
        ),
        migrations.CreateModel(
            name='PaperQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_order', models.PositiveIntegerField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_questions', to='papergen.generatedpaper')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_appearances', to='question_bank.question')),
            ],
            options={
                'ordering': ['question_order'],
                'unique_together': {('paper', 'question_order')},
            },
        ),
    ]
