# Generated by Django 5.0.14 on 2026-09-22 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institute', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('SHORT', 'Short Answer'), ('LONG', 'Long Answer')], default='SHORT', max_length=10)),
                ('options', models.JSONField(blank=True, help_text='For MCQ only: list of options, e.g. ["Paris", "London", "Rome", "Berlin"]', null=True)),
                ('answer', models.TextField(help_text='Correct answer / model answer used for the answer key.')),
                ('marks', models.PositiveIntegerField(default=1)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_date', models.DateField(blank=True, help_text='Last time this question appeared in a generated paper.', null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='institute.chapter')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['chapter', 'difficulty', 'question_type'], name='question_ba_chapter_0401be_idx')],
            },
        ),
    ]
