# Generated by Django 5.0.14 on 2026-09-22 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institute', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('UNIT_TEST', 'Unit Test'), ('HALF_YEARLY', 'Half-Yearly'), ('FINAL', 'Final Examination')], max_length=20)),
                ('total_marks', models.PositiveIntegerField()),
                ('structure', models.JSONField(help_text='List of requirement rows, e.g. [{"difficulty": "EASY", "question_type": "MCQ", "marks": 1, "count": 5}, {"difficulty": "MEDIUM", "question_type": "SHORT", "marks": 3, "count": 5}, {"difficulty": "HARD", "question_type": "LONG", "marks": 5, "count": 4}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprints', to='institute.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
