# Generated by Django 5.0.14 on 2026-09-22 04:19

import django.db.models.deletion
import submissions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institute', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(help_text='e.g. Unit Test 1, Half-Yearly, Final', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Any instructions for the Admin.')),
                ('handwritten_pdf', models.FileField(upload_to=submissions.models.handwritten_upload_path)),
                ('finalized_pdf', models.FileField(blank=True, null=True, upload_to=submissions.models.finalized_upload_path)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('PROCESSED', 'Processed'), ('PAID', 'Paid & Downloaded')], default='SUBMITTED', max_length=10)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('processed_on', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_submissions', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='institute.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_on'],
            },
        ),
    ]
